http:
 listener:
  host: "localhost"
  port: "9081"
  
db:
 sf:
  name: "SBMQKDP-TT42813"
  warehouse: "COMPUTE_WH"
  database: "MYDATABASE"
  schema: "TEST"
  user: "Narsi"
  password: "Narsi@123456789"
  role: "ACCOUNTADMIN"

email:
  confg: 
   host: "smtp.gmail.com"
   port: "587"
   user: "narsingbeesetti06@gmail.com"
   password: "kejo yanz wjpo vnum"
   key: "mail.smtp.starttls.enable"
   value: "true"
