#
# This action is triggered manually. Either a specific release tag to deploy to production is specified or the
# latest release will be deployed.
#
 
name: "Deploy Release to PROD"
# Controls when the action will run.
on:
  workflow_dispatch:
    inputs:
      release_number:
        description: 'Version to Release (Ex: v1.0.0). Default is LATEST.'
        required: false 
        default: 'LATEST'
# just call the common flow
jobs:
  call-mule-deploy-prod:
    uses: Narsing-s/.github/workflows/mule-deploy-prod.yml@v1.0.15
